project_name: color-picker
builds:
  - env:
      - CGO_ENABLED=0
      - "GO111MODULE=on" # make sure to use go modules
      - "GOFLAGS=-mod=readonly -trimpath" # trimpath helps with producing verifiable binaries
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  # https://goreleaser.com/deprecations/#archivesreplacements
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end}}

checksum:
  name_template: 'sha256sum.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'

release:
  github:
    owner: "fahlmant"
    name: "color-picker"
  prerelease: auto
